### ISSUE TITLE
ISO OID acronym

### ISSUE THREAD

**Issue by danielmarschall** [ietf-wg-uuidrev/rfc4122bis#117]
Hello,

In 2020, I reported [errata 6225 for RFC4122](https://www.rfc-editor.org/errata/eid6225)

The errata is mentioned in the changelog of "draft-00", so I guess it was fixed. Thank you for this change.

However, there is another reference where it says "ISO OID", in Appendix A.  It should be called "Object Identifier (OID)".

I also mentioned in Errata 6225, that I think it would be important to define how the OID should be defined, so I think it should mention in parentheses "In dot-notation without leading dot, e.g. **2.999**".

What do you think?

**Comment by danielmarschall** [comment]
(You can completely delete issue #117 since I have created a pull request #118. I thought these would automatically merge and not generate a new issue number).

**Comment by mcr** [comment]
> (You can completely delete issue #117 since I have created a pull request #118. I thought these would automatically merge and not generate a new issue number).

They merge if you say something like close #117.
