### ISSUE TITLE
Errata: Better Clarify network byte order when referencing most significant bits | 3546

### ISSUE THREAD

**Issue by kyzer-davis** [ietf-wg-uuidrev/rfc4122bis#12]
### Errata ID: [3546](https://www.rfc-editor.org/errata/eid3546)
- Status: Held for Document Update
- Type: Technical
- Publication Format(s) : TEXT
- Reported By: Askar Safin
- Date Reported: 2013-03-14
- Held for Document Update by: Barry Leiba
- Date Held: 2013-03-20

### Errata
Section 4.1.3 says:

```
The version number is in the most significant 4 bits of the time
stamp (bits 4 through 7 of the time_hi_and_version field).
```

It should say:

```
The version number is in the most significant 4 bits of the time
stamp (bits 0 through 3 of the time_hi_and_version field).
```

### Notes:

We use network order (as far as I know, we use network order in this RFC both for bits and bytes). So, the most significant bits comes first and they are located in first bytes. So, 0 through 3.

### VERIFIER NOTES
This erratum is correct as far as it goes, but, given other text in the RFC, so is erratum 1957. There is a pervasive problem in this RFC with inconsistent and unclear usage of bit numbering, which switches between several conventions. The diagram in Section 4.1.2 uses left-to-right bit numbering (the most significant bit is numbered 0), but much of the text (such as in Section 4.2.2) uses right-to-left bit numbering (the least significant bit is numbered 0). Most of the text uses big-ending byte order (network byte order), but some seems to assume little-ending, probably mistakes that come from the authors' familiarity with that convention.

With respect to the text in question, the first sentence of Section 4.1.3, we have the following situation:

- The original text is correct if we assume right-to-left bit numbering and little-endian byte order.

- Erratum 1957 is correct if we assume right-to-left bit numbering and big-endian byte order. This change also makes the first sentence of Section 4.1.3 consistent with the sixth bullet in Section 4.2.2.

- Erratum 3546 is correct if we assume left-to-right bit numbering and big-endian byte order.

In the end, the real point is that this document needs a revision that carefully and thoroughly fixes every instance of byte numbering (or removes the byte numbering and refers only to "most significant" and "least significant"). Such a revision should also double-check the sample code in Appendix A to be sure it works in both big-ending and little-endian machines.

Happily, it's not likely that misunderstandings here will cause actual interoperability problems: this isn't a situation where things need to be disassembled and reassembled. The algorithm merely turns a UUID into a URN, and the URN is thereafter a "black box", an unchanged identifier. The only issue would be whether different interpretations of the document would turn two different UUIDs into the same URN, and, given the number of bits involved, the likelihood of collisions in practice is small.

**Comment by safinaskar** [comment]
I'm author of errata [3546](https://www.rfc-editor.org/errata/eid3546). Just now I carefully have read relevant fragment of https://www.ietf.org/archive/id/draft-ietf-uuidrev-rfc4122bis-00.txt , i. e. this paragraph:

> The version number is in the most significant 4 bits of octet 6.
   More specifically bits 48 through 51.  The remaining 4 bits of Octet
   6 are dynamic.

So, I'm sure this errata (regarding this paragraph) is fixed. Thanks a lot.

Also, it seems bits and bytes numbers are zero-based. I don't see mentions of this starting from begin of this document through this paragraph

**Comment by kyzer-davis** [comment]
> So, I'm sure this errata (regarding this paragraph) is fixed. Thanks a lot.

Thanks for the confirmation @safinaskar 

> Also, it seems bits and bytes numbers are zero-based. I don't see mentions of this starting from begin of this document through this paragraph

I have this paragraph in Section 5 (being moved to section 4). I believe when moved to the correct spot this should address your concern.

```
While discussing UUID field layouts, bit definitions start at 0 and end at 127 while octets definitions start at 0 and end at 15.
```
Source, https://www.ietf.org/archive/id/draft-ietf-uuidrev-rfc4122bis-00.html#section-5

**Comment by safinaskar** [comment]
> I believe when moved to the correct spot this should address your concern.

Yes, I see
