### ISSUE TITLE
Binary prefix usage in prose

### ISSUE THREAD

**Issue by tgross35** [ietf-wg-uuidrev/rfc4122bis#125]
Is there any precedent for adding a prefix such as `0b` to indicate that a number is presented in binary? There are a handful of places where I could see this making sense, for example in section 5.6

```
   var:
      The 2 bit variant field as defined by Section 4.1 set to 10.
      Occupies bits 64 and 65 of octet 8.
```

I would find it more clear to see `set to 0b10`, confirming the value to be a decimal 2 rather than decimal 10.

**Comment by kyzer-davis** [comment]
Yeah, we have a few places where 0b is defined (mostly in the appendix test vectors) but I can see the value here. I will sneak it in.
