### ISSUE TITLE
Clarify Hash Space IDs listed are not the only options

### ISSUE THREAD

**Issue by danielmarschall** [ietf-wg-uuidrev/rfc4122bis#132]
It's probably too late for any amendments, so maybe it will only be an errata after publishing instead.

_Appendix B:
This appendix lists **_the_** hash space IDs for use with UUIDv8 name-based UUIDs._
=> The word "the" suggests that there can only be these hash space IDs and nothing else.

In comparison:
_Appendix A:
This appendix lists **the** name space IDs **for some** potentially interesting name spaces_ 
=> so appendix A implies that there can be many name space IDs.

My suggestion is that for Appendix B, remove the word "the" or replace it is "some", to imply that there can be other hash space IDs. (I guess this was your intention)

**Comment by kyzer-davis** [comment]
Yeah, I can sneak that in to my open PR.
