### ISSUE TITLE
Move UUIDv8 Examples out of Test Vectors

### ISSUE THREAD

**Issue by ben221199** [ietf-wg-uuidrev/rfc4122bis#150]
As seen in #144 and #147, the examples of UUIDv8 are a big issue. We should do something about it and rewrite or remove them. The reason is that the examples can now be seen as some call to action to implement them literally, and that is not what they are for.

**Comment by bradleypeabody** [comment]
@ben221199 I'd like to see how #147 plays out, and then from there we can see if there is a new example that addresses the concerns from that issue, and/or if we want to remove or adjust any other examples.   Regarding #144, I'm hoping that if we are not going to create UUIDv9 as an official hash-based UUID version right now, and just stick with UUIDv8 example(s), then it should simplify the matter, hopefully.

**Comment by ben221199** [comment]
Okay clear. We will see.

**Comment by kyzer-davis** [comment]
I have moved these out of test vectors and into their own appendix as per https://github.com/ietf-wg-uuidrev/rfc4122bis/issues/150#issuecomment-1731471692, and added lots of "here be dragons" text in https://github.com/ietf-wg-uuidrev/rfc4122bis/commit/020137452be6dcc225637f246319553e4c7ec384.
