### ISSUE TITLE
Clarify  "Name-Based" is the same as "Hash-Based"

### ISSUE THREAD

**Issue by kyzer-davis** [ietf-wg-uuidrev/rfc4122bis#154]
Tracker item so I don't forget

**Comment by fabiolimace** [comment]
Also don't forget to include a note that they are synonymous in the context of UUIDs and "name-based" is still a valid word to maintain "historical compatibility" (I don't know what to call it) with the old RFC-4122.

The only difference between the two adjectives is the concept referenced by each term. The first refers to the input argument, that is, the “name”; while the new one makes reference to the mechanism employed, that is, the hash algorithm.

Some very popular libraries use the old term in method names. A notable example is JUG's [`Generators.nameBasedGenerator()`](https://javadoc.io/doc/com.fasterxml.uuid/java-uuid-generator/4.0.1/com/fasterxml/uuid/Generators.html).

**Comment by kyzer-davis** [comment]
Yeah, good point.

**Comment by kyzer-davis** [comment]
Mauling this over a bit more. Its a matter of semantics and IMO. I am not entirely sure it is worth the change (at least this far into the doc.)
This is similar to how we didn't change "nil uuid" to "min uuid" back under some other issue tracker. 
Historically speaking we wanted to keep things consistent and I think we should use the same approach here.

**Comment by danielmarschall** [comment]
My personal opinion is keeping it name-based (including the name of the UUIDv8 example), because the term is very old and used in a lot of implementations.

Googling `"name based" uuid` results in 37.100 pages.

**Comment by fabiolimace** [comment]
Suggestion:

_Although some prefer to use the word “hash-based,” we use the adjective “name-based” here to maintain consistency with previous documents and existing implementations. However, we do not distinguish between the two terms since they both refer to the same thing._

Well, it doesn’t fall into the “small footnote” category, as it is a long paragraph. But it's just an idea.

**Comment by sergeyprokhorenko** [comment]
> The only difference between the two adjectives is the concept referenced by each term. The first refers to the input argument, that is, the “name”; while the new one makes reference to the mechanism employed, that is, the hash algorithm.

But input argument may be integer, not name at all

**Comment by fabiolimace** [comment]
> But input argument may be integer...

Yes, it can be anything.

> I'm against having sugar label on a can of lentils, ...

I also hate it when I find beans in a tub of ice cream in the fridge. But in this case, the benefit obtained from the change is irrelevant. At the end of the day, it's just a name, and most of us are used to it. Furthermore, it's not cool to fall into yet another endless semantic discussion in the final minutes of the game.

**Comment by sergeyprokhorenko** [comment]
> > But input argument may be integer...
> 
> 
> 
> Yes, it can be anything.
> 
> 
> 
> > I'm against having sugar label on a can of lentils, ...
> 
> 
> 
> I also hate it when I find beans in a tub of ice cream in the fridge. But in this case, the benefit obtained from the change is irrelevant. At the end of the day, it's just a name, and most of us are used to it. Furthermore, it's not cool to fall into yet another endless semantic discussion in the final minutes of the match.
> 
> 
> 
> P.S. IMHO.

Not everyone has such a habit of the name. They read the standard literally, and this can lead to errors

**Comment by kyzer-davis** [comment]
I can add a line about hash-based vs name-based meaning the same thing. I will do it in the branch with all the other hash-based/named-based changes.
Give me a sec. Does it work if I place it at the start of "Name-Based UUID Generation" section that way I don't have to double text?

**Comment by kyzer-davis** [comment]
Added, https://github.com/ietf-wg-uuidrev/rfc4122bis/issues/154#issuecomment-1731579688,  to new branch via https://github.com/ietf-wg-uuidrev/rfc4122bis/commit/11fecf8b634720a378eef5377ab4b76f1798e954
