### ISSUE TITLE
Expand v8 Time-based Example to larger timestamp

### ISSUE THREAD

**Issue by kyzer-davis** [ietf-wg-uuidrev/rfc4122bis#159]
For the time-based example, here are alternatives (I am keeping 1 nano second):

A. `tttttttt-tttt-Xttt-rrrr-Xrrrrrrrrrrr` : 1 nano second in 60 bits = wraps after 36 years (`2^60/(1000*1000*1000*60*60*24*365)`), and has 62 bits are left for random (i.e. chance to collide is 1/2^62)

B. `tttttttt-tttt-Xttt-trrr-Xrrrrrrrrrrr` : 1 nano second in 64 bits = wraps after 584 years (`2^64/(1000*1000*1000*60*60*24*365)`), and has 58 bits are left for random (i.e. chance to collide is 1/2^58)

C. `tttttttt-tttt-Xttt-ttrr-Xrrrrrrrrrrr`: 1 nano second in 68 bits = wraps after 9359 years (`2^68/(1000*1000*1000*60*60*24*365)`), and has 54 bits are left for random (i.e. chance to collide is 1/2^54)

D. `tttttttt-tttt-Xttt-tttt-Xrrrrrrrrrrr` : 1 nano second in 76 bits = wraps after 2395924 years (`2^76/(1000*1000*1000*60*60*24*365)`), and has 46 bits are left for random (i.e. chance to collide is 1/2^46)

My preferrence would be >=100 years, so 64 bit.

_Originally posted by @danielmarschall in https://github.com/ietf-wg-uuidrev/rfc4122bis/issues/147#issuecomment-1739901324_

Reasons: The current example wraps in a few hours, few more bits make it a better example.

**Comment by kyzer-davis** [comment]
I am fine with either 60 or 64; 
- 60: `custom_a` and `custom_b` that is the easiest for me to modify the text. 
- 64: Makes sense to as I just lay down all the bits as is in order through custom a/b/c, little bit more work in editing.

Personally, if nobody objectsI will go with what is easier thus:
> `custom_a` and `custom_b` is filled with `0x16D6320C3D4DCC00` being:
> `6D6320C3D4DCC00` fills out those 60 bits thus `6D6320C3-D4DC-8C00-8EC9-32D5F69181C0` is the example.

I will revising leading text based on whatever is chosen.

**Comment by kyzer-davis** [comment]
Before I leave for the day: 
I cannot stress how much we do not need to over-iterate on this.
A few more bits to the timestamp and random for the rest. Let's not cook up a million complex scenarios for an appendix item.

**Comment by danielmarschall** [comment]
> A few more bits to the timestamp and random for the rest. Let's not cook up a million complex scenarios for an appendix item.

Agreed! The example should be as simple as possible. Filling `custom_c` with half random and half time-stamp is too complex, so 60 bits might be better.

On the other hand, I think >100 years is good to avoid creating a "year 2038" situation (i.e. a wrap-around which we might experience during our lifetime).

How about "10ns in 60bits", which would wrap around in 365 years?

I am fine with either "1ns in 60bits (36 years wrap)" or "10ns in 60bits (365 years wrap)", but prefer the latter.
