### ISSUE TITLE
Describe allocation logic of Namespace ID

### ISSUE THREAD

**Issue by kyzer-davis** [ietf-wg-uuidrev/rfc4122bis#161]
Action item to describe how current Namespace IDs are allocated and methods for adding a new ID following the same logic. 
Ties into #144 to complete the topic.

**Comment by kyzer-davis** [comment]
@danielmarschall, @bradleypeabody, @mcr, et all.
With the inclusion of some normative language in this appendix. I think I should move this up out of the appendix and into a section. Say after or within the "Name-Based UUID Generation" section?

Any objection to that change?

**Comment by danielmarschall** [comment]
Good idea. Yes, I think IANA registration related things should be outside of appendixes.

**Comment by kyzer-davis** [comment]
I went ahead and moved it via https://github.com/ietf-wg-uuidrev/rfc4122bis/pull/162/commits/bd2a5e770b23e7f29b152600684cc41f96f4bd70. 
I collapsed the "a note on names" subsection into that new section as well to keep that all in the same location.
This probably should have been a different PR but its too late now...
