### ISSUE TITLE
Change RFC8937 and RFC4086 to Informative References

### ISSUE THREAD

**Issue by jimfenton** [ietf-wg-uuidrev/rfc4122bis#163]
RFC 8937 is an informative RFC, and therefore not appropriate to be a normative reference from a standards-track RFC. This was pointed out by the Nits tool.

IMO, the advice on choosing random numbers in Section 6.8 is informative, and [RFC8937] and [RFC4086] should be informative for the same reason as [RANDOM] is.

On a related topic, while [RANDOM] seems to be a very good treatment of the subject, I'm a bit concerned about it not being an archival document. What should readers do if it goes away? Find it on Internet Archive?

**Comment by kyzer-davis** [comment]
> On a related topic, while [RANDOM] seems to be a very good treatment of the subject, I'm a bit concerned about it not being an archival document. What should readers do if it goes away? Find it on Internet Archive?

I had added the RFCs as alternatives to RANDOM for this very reason. At one point it was JUST random and I wanted to provide some other citations in the event something happens.
