### ISSUE TITLE
RFC 5234

### ISSUE THREAD

**Issue by cabo** [ietf-wg-uuidrev/rfc4122bis#38]
`The formal definition of the UUID string representation is provided by the following ABNF [[RFC4234](https://ietf-wg-uuidrev.github.io/rfc4122bis/draft-00/draft-ietf-uuidrev-rfc4122bis.html#RFC4234)]:`

Etc. are wrong.

**Comment by cabo** [comment]
(idnits is a useful tool that quickly finds things like this.
Available via <https://author-tools.ietf.org>.)

**Comment by kyzer-davis** [comment]
Thanks, covered under #25 for Draft 01
