### ISSUE TITLE
Draft 03: Fix "integral numbers of octets" verbiage

### ISSUE THREAD

**Issue by kyzer-davis** [ietf-wg-uuidrev/rfc4122bis#67]
Before: 
> To minimize confusion about bit assignments within octets and among differing versions, the UUID record definition is defined only in terms of fields that are integral numbers of octets. 

After:
> To minimize confusion about bit assignments within octets and among differing versions, the UUID record definition is provided as a a grouping of fields within bit layout consisting four octets to a row.

Edit: Updated grammar as per @cbandy comment.

**Comment by cbandy** [comment]
"is provides as a a grouping" → "is provided as a grouping", perhaps?

"consisting four octets octets" → "consisting of four octets", perhaps?
