### ISSUE TITLE
Draft 03: Downgrade MUST NOT to SHOULD NOT for guessability of UUIDs

### ISSUE THREAD

**Issue by kyzer-davis** [ietf-wg-uuidrev/rfc4122bis#75]
> Section 9, “Implementations MUST NOT assume that UUIDs are hard to guess.” 
> This would mean that it’s not permissible to use a randomly generated UUID for something like a session cookie. 
> On the other hand, NIST currently considers a random value generated 
> from a CSPRNG with a security  strength of at least 112 bits to be 
> effectively unguessable (see SP 800-131A), and a version 4 UUID meets that requirement. This prohibition seems a little strong.

This is the RFC4122 verbiage but we could downgrade to a SHOULD NOT.

**Comment by mcr** [comment]
I think that if someone needs something that is hard to guess, they need to be responsible for making sure.
I think that the point of this disclaimer is that not all UUIDs are hard to guess, and we don't want people confused.
