### ISSUE TITLE
Limiting size of additional clock precision (method 4) for v7

### ISSUE THREAD

**Issue by LiosK** [ietf-wg-uuidrev/rfc4122bis#86]
(Copied from my email to uuidrev@ietf.org to add a relevant but different topic)

I would propose to limit the size of Increased Clock Precision (6.2. Monotonicity and Counters: Method 4) to a certain number of bits, say 12 bits, for the UUIDv7 purpose. I really like the idea of the additional clock precision encoded using the fractional representation, but I'd like to point out a potential concern about universal uniqueness and usability.

The v7 scheme currently relies on randomness for universal uniqueness. On the other hand, a timestamp is not a source of randomness but is a shared piece of information across multiple generators. The timestamp field provides the universal uniqueness property by relying on the timing of generation, not randomness, so two timestamps collide if two generators generate IDs exactly at the same time, even if they employ picosecond timestamps. In other words, the timestamp and randomness both offer universal uniqueness but through different mechanisms.

In my opinion, UUIDv7 is more useful for users if the RFC sticks to the randomness mechanism to guarantee universal uniqueness. If the spec mixes the two mechanisms, then users have to take care of the timing of generations or the configuration of PRNGs depending on the implementation of a UUIDv7 generator, which introduces additional complexity to just get a time-ordered UUID. So, I believe the standard should limit the maximum size of extra clock precision to guarantee that a sufficient bit space is reserved for the randomness field.

It would be hard to set an appropriate limitation, but 12 bits might be a good starting point. By limiting the size of method 4 clock precision to 12 bits, we can guarantee the same level of randomness (62 bits) as UUIDv6 while accepting microsecond-precision timestamps. Applications that need finer timestamps are likely to be specialized use cases and should generally resort to UUIDv8.

**Comment by LiosK** [comment]
Is it possible to replace the following text in Replace Left-Most Random Bits with Increased Clock Precision (Method 4):

> Using floating point math, multiply this fraction of a millisecond value by <del>4095</del> and round to an integer result to arrive at a number between 0 and the maximum allowed for the indicated bits which is sorts monotonically based on time.

To:

> Using floating point math, multiply this fraction of a millisecond value by <ins>4096</ins> and round <ins>down</ins> to an integer result to arrive at a number between 0 and the maximum allowed for the indicated bits which is sorts monotonically based on time.

The latter logic is expressed in Python as follows:

```python
submsec_float = 0.4567
submsec_frac_bin_from_float = int(submsec_float * 0b1_0000_0000_0000)

assert submsec_frac_bin_from_float == 1870
```

And, it allows the faster integer math computation:

```python
submsec_nsec = 456700  # 0.4567 milliseconds expressed as nanosecond-precision ticks
submsec_frac_bin_from_nsec = (submsec_nsec << 12) // 1_000_000

assert submsec_frac_bin_from_nsec == 1870
```

The latter logic is more friendly with the `clock_gettime` C function than the original approach. Plus, the original is less useful in that it requires the floating-point math for rounding.

Please also find a quick Rust code that demonstrates a couple of techniques to arrive at the binary fractional representation of a submillisecond timestamp.

```rust
const SUBMSEC_SIZE: u64 = 12;
const SUBMSEC_MASK: u64 = (1 << SUBMSEC_SIZE) - 1;

// iterate subsecond timestamp ticks of nanosecond resolution over one second, emulating all
// the possible `tv_nsec` values returned by `clock_gettime(3)`
for tv_nsec in 0u64..1_000_000_000 {
    let _msec = tv_nsec / 1_000_000;
    let submsec = tv_nsec % 1_000_000;

    // get fractional submsec representation using floating-point math
    let submsec_fraction = submsec as f64 / 1_000_000f64;
    let result_fp = (submsec_fraction * (1 << SUBMSEC_SIZE) as f64).trunc() as u64;

    // get fractional submsec representation using integer math
    let result_int = (submsec << SUBMSEC_SIZE) / 1_000_000;
    assert_eq!(result_fp, result_int);

    // get fractional submsec representation directly from `tv_nsec`
    let result_from_nsec = ((tv_nsec << SUBMSEC_SIZE) / 1_000_000) & SUBMSEC_MASK;
    assert_eq!(result_fp, result_from_nsec);
}
```

**Comment by LiosK** [comment]
The introduction of Method 4 seems to require some updates to [5.7. UUID Version 7](https://www.ietf.org/archive/id/draft-ietf-uuidrev-rfc4122bis-03.html#name-uuid-version-7):

---

> UUID version 7 also has improved entropy characteristics over versions 1 or 6.

This statement in the first paragraph no longer holds unless the size of Method 4 timestamp is limited to 11 bits or less.

---

> rand_a:
> 12 bits pseudo-random data to provide uniqueness as per Section 6.8 and/or an optional counter to guarantee additional monotonicity as per Section 6.2.
>
> var:
> (snip)
>
> rand_b:
> The final 62 bits of pseudo-random data to provide uniqueness as per Section 6.8 and/or an optional counter to guarantee additional monotonicity as per Section 6.2.

The explanation of rand_a and rand_b has to be updated to accept the Method 4 timestamp. Perhaps, we should add some clarifying text like:

> The rand_a and rand_b fields, jointly, MUST be filled with a combination of the following subfields, in this order:
>
> 1.  An OPTIONAL submillisecond timestamp (up to 12 bits) to utilize extra clock resolution as per Section 6.2 (Method 4).
> 2.  An OPTIONAL counter to guarantee additional monotonicity as per Section 6.2 (Method 1 or 2).
> 3.  Random data to provide uniqueness as per Section 6.8.

**Comment by bradleypeabody** [comment]
@LiosK 
Regarding this proposed text:

> Using floating point math, multiply this fraction of a millisecond value by 4096 and round down (toward zero) to an integer result to arrive at a number between 0 and the maximum allowed for the indicated bits which is sorts monotonically based on time.

I totally agree, rounding down is better here - more explicit and easier to understand.  I'm 100% good with that change.

On the other text changes, my concerns are:
* Language like "The rand_a and rand_b fields, jointly, MUST be filled with a combination of the following subfields" I think is too strict.  E.g. if some vendor wants to put some server node ID in here somewhere, we shouldn't explicitly prohibit that if it doesn't interfere with the basic parsing properties (in other words the random part is just random, if the generator wants to do something a bit different lose some entropy in the process - that's up to them - see the Global and Local Uniquess section).
* I don't entirely agree that CSPRNG data is fundamentally going to result in less random data.  Let's say we have 12 bits that are generated with a CSPRNG and 12 bits which are a fraction of a millisecond - is there some mathematical property which says that it is less likely that the CSPRNG values will collide than two IDs will be generated in the exact same instant?  I realize some clocks may have less granularity available, but that's exactly why we want to make the length implementation dependent.  In general, I would be okay with suggesting 12 bits as a recommended length, but I think putting an absolute limit on there is too restrictive. If people want to put more precise clock data in there to express a more specific timestamp, and let's say due to clock granularity problems this reduces entropy, I think this is a tradeoff an implementation should be allowed to make.

In terms of workflow on some of these, for specific text changes it might be easier to just do a pull request and you can also link to it here - but that way the exact changes can be discussed and if there is consensus just merged in.

**Comment by LiosK** [comment]
> I totally agree, rounding down is better here

Will craft a PR for this!

> Language like "The rand_a and rand_b fields, jointly, MUST be filled with a combination of the following subfields" I think is too strict.

Would propose an alternative wording: "The rand_a and rand_b fields, jointly, <del>MUST be</del><ins>are</ins> filled with a combination of the following subfields". It doesn't change a lot, but yeah the overall 5. UUID Layouts section doesn't really employ the MUST verbiage, so v7 should definitely follow that tone.

However, it is questionable whether compliant implementations may embed a node ID in UUIDv7; my understanding is no, they can't. It is not 100% clear because the UUID Layouts section doesn't use the BCP 14 verbiage, but it reads like none of the UUID versions other than v8 accepts a node ID inside the 128-bit space. In the literal sense, 5.4. UUID Version 4 section doesn't preclude to include a timestamp and node ID in it, but I don't think a generator that constructs a UUIDv4 from a 60-bit timestamp and 60-bit node ID is an RFC-compliant generator. Similarly, I don't believe a UUIDv7 MAY contain a node ID. Technically, [6.4. Distributed UUID Generation](https://www.ietf.org/archive/id/draft-ietf-uuidrev-rfc4122bis-03.html#section-6.4) referred to by [6.7. Global and Local Uniqueness](https://www.ietf.org/archive/id/draft-ietf-uuidrev-rfc4122bis-03.html#section-6.7) reads "Implementations that choose to leverage an embedded node id SHOULD utilize UUIDv8.", but SHOULD here is in effect MUST, I think.

> I think this is a tradeoff an implementation should be allowed to make.

I totally agree that the randomness vs. granular timestamp is a trade-off issue. Perhaps, there is no theoretical advantage of one option over the other, but still I believe putting an absolute limit to the timestamp would increase the overall utility of UUIDv7 for general users.

Once finalized, v7 will become popular, many implementations will emerge, and many users will use it. As a common ground, it would be helpful if the standard is clear that the uniqueness of UUIDv7 is solely dependent on CSPRNGs and reserves sufficient space for CSPRNG inputs. Then, users just need to pick a compliant library and make sure their CSPRNG is working properly. Otherwise, users have to examine the library before use to understand the source of uniqueness and satisfy all the prerequisites for that specific implementation. This could sound like an extreme, but a standard exists to coordinate implementers and users, so clarifying the responsibility boundary should be helpful. Those who want to utilize a granular timestamp should resort to UUIDv8.

This is my personal opinion, and consensus is definitely needed.

I admit my opinion is somewhat biased by the [recent government scandal in my country](https://www.asahi.com/ajw/articles/14904344), where timestamp collisions caused private information leakage. Microsecond timestamps reportedly collide multiple times in the incident. It is seemingly very difficult to ensure the timestamp granularity across a system. For example:

- client or server hardware or operating systems might not support granular timestamp
- mice and keyboards operate on a certain timing clock and might transmit users' input at a certain cycle
- routers and network switches store packets in their buffer and might send multiple requests to the server at once

Learning these cases recently, I feel kind of fearful to rely deeply on timestamps to guarantee uniqueness and randomness.

**Comment by mcr** [comment]
> Once finalized, v7 will become popular, many implementations will emerge, and many users will use it. As a common ground, it would be helpful if the standard is clear that the uniqueness of UUIDv7 is solely dependent on CSPRNGs and reserves sufficient space for CSPRNG inputs. Then, users just need to pick a compliant library and make sure their CSPRNG is working properly. Otherwise, users have to examine the library before use to understand the source of uniqueness and satisfy all the prerequisites for that specific implementation. This could sound like an extreme, but a standard exists to coordinate implementers and users, so clarifying the responsibility boundary should be helpful. Those who want to utilize a granular timestamp should resort to UUIDv8.
> 

I completely agree with you here.
