### ISSUE TITLE
Limitations of 32 bit unix epoch in UUID V7

### ISSUE THREAD

**Issue by crc-sstubbs** [ietf-wg-uuidrev/rfc4122bis#99]
Hi,

Not sure if this is the correct place to add this but I'm truly excited to see these being used in the future. Reading through the draft would UUID V7 which I am intending to use in the future experience the 2038 problem?

**Comment by kyzer-davis** [comment]
Hello! 
Take a look at the "length" sub-section of Section 6.1 Timestamp Considerations:
https://www.ietf.org/archive/id/draft-ietf-uuidrev-rfc4122bis-04.html#name-timestamp-considerations-3

**Comment by crc-sstubbs** [comment]
Thank you! I missed that while looking through. 48 bit is perfect.
